name: Book CROSS TRAINING for THU 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '30 16 * * 2' # Runs every tuesday at 17:30h to book the class for Thursday at 17:45 // Winter time 1h diff

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:45'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
